export const pilot=[
 {title:'Your story, in two minutes.',focus:'Find your starting point',speak:'Tell me about yourself. Connect your experience to the kind of product problems you want to solve next. Use one verified example.',recall:'Explain what makes a design decision different from a visual preference.',challenge:'Improve the first five minutes of a complex workplace tool for a new employee.',craft:'Pick one dashboard you know. Sketch its information hierarchy. What should the user notice first, and why?',story:'Choose a project. Separate what you personally decided from what the team did. List evidence you could show.',social:'Ask someone about a product they used today. Ask one follow-up, then share a related observation.',review:'Save your first take. Note one clear moment and one sentence you would simplify.'},
 {title:'Start with a better question.',focus:'Problem framing',speak:'Tell me about a time the requested feature was different from the underlying user need.',recall:'Explain the difference between a user request, a user problem, and a business outcome.',challenge:'A team asks you to add AI search to its help centre. Decide what you need to learn before designing.',craft:'Sketch two versions of a search empty state: no matching results and no permission to view results.',story:'Record the original request, your reframing, the evidence, and what changed. Label assumptions.',social:'Ask a colleague or friend what makes a recurring task difficult. Follow up on a concrete recent example.',review:'Did you ask about behaviour before proposing a solution? Repeat your opening in 30 seconds.'},
 {title:'Make a choice. Explain the cost.',focus:'Alternatives and trade-offs',speak:'Explain a decision where two reasonable approaches competed. Why did you choose one?',recall:'Name a case where a conventional pattern is right and a case where it is limiting.',challenge:'Design a way to reschedule ten appointments. Compare editing individually, bulk editing, and proposing an intent.',craft:'Sketch a dense table and a card layout for the same task. Compare scanning, comparison, and action.',story:'Write the alternative you rejected, its strongest advantage, and the cost your chosen approach accepted.',social:'Offer your opinion on a small decision and ask, “How do you see it?” Listen before responding.',review:'Listen for a real trade-off. If your alternative sounds obviously bad, make it more credible.'},
 {title:'Give the details a reason.',focus:'Interaction and visual craft',speak:'Critique an interface you use. Explain what it does well before prioritising one improvement.',recall:'Explain hierarchy, feedback, and recovery through one interaction.',challenge:'Redesign a settings workflow for someone using large text and a keyboard.',craft:'Create default, focus, loading, success, error, and recovery states for one important action.',story:'Choose a craft decision. Defend its hierarchy, spacing, content, and responsive behaviour.',social:'Show a peer one screen. Ask what they notice first and what they expect to happen next.',review:'Distinguish observed behaviour from your hypothesis. What would you need to validate?'},
 {title:'Design trust into the workflow.',focus:'AI and technical fluency',speak:'Explain where an AI assistant should suggest, where a person should approve, and where software must enforce rules.',recall:'Explain latency, permissions, and stale data without engineering jargon.',challenge:'An AI service-desk assistant recommends closing a ticket. Design review, approval, failure, and undo.',craft:'Sketch a streaming suggestion that cites its source and handles an unavailable source gracefully.',story:'Describe an AI or automation prototype honestly. Separate demonstrated behaviour from production readiness.',social:'Explain a technical idea to someone outside design. Ask them which part needs a clearer example.',review:'Did you explain why AI is useful and what happens when it is wrong? Retry with a concrete failure.'},
 {title:'Stay clear when challenged.',focus:'Influence and adaptation',speak:'Tell me about a disagreement. Explain what changed your mind or how the final decision was made.',recall:'Describe the difference between influence, decision ownership, and consensus.',challenge:'Your research contradicts the direction you presented yesterday. Plan the next conversation and experiment.',craft:'Explain one design to a peer. Ask them to interrupt twice with “why?” and “what evidence?”',story:'Write what the other person was optimising for, your contribution, and the outcome you can substantiate.',social:'Arrange a ten-minute critique or mock interview. Practise acknowledging a challenge before answering.',review:'Find a moment where you became defensive or vague. Record a calmer, more specific response.'},
 {title:'Meet your first-week self.',focus:'Review and repeat',speak:'Repeat your day-one introduction using the same two-minute limit. Keep both recordings.',recall:'Without notes, explain problem, evidence, options, decision, trade-off, and outcome.',challenge:'Repeat the workplace onboarding problem from day one. Now assume intermittent connectivity.',craft:'Compare your first and latest sketches. Identify one improvement in hierarchy and one unresolved state.',story:'Tell your strongest story, then answer: What did you personally do? What can you not claim?',social:'Ask a trusted person to compare your two introductions for clarity and specificity.',review:'Choose one strength to keep and one skill to practise next week. Compare evidence, not just confidence.'}
];
export const phases=[
 {name:'Foundations',start:1,end:15,topics:['Baseline and career narrative','Problem framing','Alternatives and trade-offs','Interaction and visual critique','AI trust and system boundaries','Influence and interruption','First weekly review','Research method selection','Jobs and mental models','Journey mapping and service blueprints','Information architecture','Navigation and search','Forms and validation','Accessibility and inclusion','Metrics and experimentation']},
 {name:'Craft and design systems',start:16,end:25,topics:['Hierarchy and density','Typography and layout','Colour and visual semantics','Motion and feedback','Responsive and cross-device behaviour','Component states and APIs','Tokens and themes','Governance and contribution','Design QA and implementation parity','Craft critique and peer review']},
 {name:'Product judgment',start:26,end:35,topics:['Prioritisation under constraints','Consumer product challenge','Enterprise workflow challenge','Search and discovery challenge','Mobile and offline challenge','Public-service challenge','Commerce and conversion','Collaboration and permissions','Reframing conventional solutions','Product design mock']},
 {name:'AI and technical fluency',start:36,end:42,topics:['Probabilistic and deterministic behaviour','Inputs, context, and grounding','Human approval and authority','Latency, streaming, and cancellation','Memory, privacy, and permissions','Evaluation and failure recovery','AI collaboration mock']},
 {name:'Portfolio and leadership',start:43,end:49,topics:['Portfolio evidence audit','Case-study narrative','Five whys of design defence','Conflict and influence','Mentoring and quality standards','Failure and learning','Portfolio mock and peer feedback']},
 {name:'Apple practice lens',start:50,end:54,topics:['Native patterns and restraint','Touch, pointer, and keyboard','Dynamic Type and accessibility','Continuity and cross-device state','Apple craft mock']},
 {name:'Google and Atlassian lenses',start:55,end:58,topics:['Scale and multilingual discovery','Evidence, metrics, and experiments','Enterprise roles and service management','AI service-desk mock']},
 {name:'Interview rehearsal',start:59,end:60,topics:['Full interview rehearsal','Repeat baseline and plan next steps']}
];
export const roadmap=phases.flatMap(p=>p.topics.map((topic,i)=>({day:p.start+i,topic,phase:p.name})));
export const interruptions=['What evidence supports that?','What did you personally decide?','Why not a simpler approach?','Engineering says this takes 18 months. What changes?','Research contradicts your assumption. How do you respond?','Now assume unreliable connectivity.','Remove AI entirely. What still works?','The completion metric improved but retention dropped.','What happens with a screen reader?','Show me another approach.','What would make you change your mind?','What did you deliberately remove?'];
export const behaviors=['Tell me about yourself.','Why this role and company?','What makes your contribution senior?','Describe a decision made with incomplete evidence.','Tell me about a disagreement with a PM.','Tell me about a disagreement with engineering.','When did research change your direction?','Describe a project that failed.','Tell me about a scope cut you made.','When did you influence without authority?','How did you raise the quality bar?','Describe a time you mentored a designer.','How did you handle a missed deadline?','Tell me about a difficult stakeholder.','Describe a decision with no access to users.','When did you prioritise accessibility?','Describe a design-system contribution.','When did you challenge a roadmap priority?','What did you learn after release?','Describe a metric that was misleading.','Tell me about a time you changed your mind.','When did you choose a familiar pattern?','When did you break a convention?','How did you resolve competing user needs?','Tell me about a critique you found difficult.','Describe a technical constraint that improved your design.','When did you delegate meaningful ownership?','Tell me about an AI failure you designed for.','What would you change in your portfolio today?','What can you not claim about your strongest project?'];
export const challengeSeeds=[
 ['Warm-up','Consumer','Make multiple alarms easier to manage','Design for someone whose wake-up schedule changes each week.','Recurring rules can become hard to predict.','Compare individual alarms, a weekly schedule, and an intent-based setup. Keep overrides visible.'],
 ['Warm-up','Craft','Recover a failed payment','A customer is unsure whether their payment succeeded.','A retry may create a duplicate transaction.','Separate pending, confirmed, and failed states. Preserve the order and explain the safe next step.'],
 ['Warm-up','Search','Improve a no-results page','Help a shopper recover when a search returns nothing.','Irrelevant recommendations can conceal the actual failure.','Offer query correction and useful ways to broaden scope without claiming results are exact.'],
 ['Warm-up','Enterprise','Invite a teammate','Make inviting a colleague to a workspace clear and safe.','An invitation can grant unintended permissions.','Make role, workspace, and pending status understandable. Include revoke and resend.'],
 ['Warm-up','Craft','Explain an empty dashboard','Design the first visit before a product has any data.','Sample data can look real.','Explain the next useful action and label any examples. Distinguish empty from failed loading.'],
 ['Warm-up','Consumer','Save a useful place','Help a traveller save somewhere they want to visit later.','Private and shared collections have different expectations.','Make saving quick, retrieval easy, and sharing deliberate.'],
 ['Warm-up','Accessibility','Improve a long form','Help a person complete a service form on a small screen.','Errors and session expiry can destroy progress.','Group meaningful steps, preserve drafts, and provide explicit labels and recovery.'],
 ['Warm-up','Craft','Make a loading state useful','A report takes 30 seconds to prepare. Design the waiting experience.','A fake progress percentage damages confidence.','Show honest state, allow leaving when feasible, and support retry or cancellation.'],
 ['Warm-up','Consumer','Reschedule an appointment','A person needs to move a booking without losing it.','The replacement slot may disappear during confirmation.','Keep the old booking until a new one is confirmed. Explain conflicts and notifications.'],
 ['Warm-up','Accessibility','Design notification controls','Help someone reduce interruptions without missing urgent events.','Too many categories make control unmanageable.','Use understandable groupings, sensible defaults, and an easy way to reverse changes.'],
 ['Senior','Enterprise','Onboard a new employee','Improve the first five minutes of a complex workplace tool.','Different roles need different starting points.','Prioritise the first meaningful task. Compare guided setup, contextual help, and role-based defaults.'],
 ['Senior','AI','Review an AI ticket resolution','Design a service-desk assistant that recommends closing a ticket.','The recommendation may be unsupported or exceed the agent’s authority.','Ground the suggestion, show relevant evidence, require appropriate approval, and enforce permissions independently.'],
 ['Senior','Search','Find one file among 50,000','Design discovery for a user who only remembers the purpose of a file.','Permissions, duplicates, and stale versions complicate results.','Compare metadata search, intent search, and contextual recents. Make scope and version clear.'],
 ['Senior','Enterprise','Bulk-edit 100 records','Help an operator update many records with different constraints.','Partial success and unintended selection can be costly.','Preview scope and changes, surface exceptions, and support recovery with an audit trail.'],
 ['Senior','Accessibility','Navigate with large text','Improve a complex settings task for a person using large text.','Truncation can hide the distinction between choices.','Preserve meaning and reading order as content reflows. Test the complete task.'],
 ['Senior','Consumer','Plan a trip together','Design collaborative travel planning for people with different budgets.','People may disagree about who can change confirmed plans.','Separate suggestions from commitments and clarify ownership, cost, and conflict resolution.'],
 ['Senior','AI','Add useful AI to email','Help someone act on a crowded inbox without losing trust.','A generated summary may omit a consequential detail.','Start with a specific job. Show source messages, editable suggestions, and clear send authority.'],
 ['Senior','Enterprise','Build an approval workflow','Let an administrator configure a multi-step approval process.','A configuration can deadlock or silently bypass a reviewer.','Preview outcomes with sample cases, validate rules, and provide versioned changes.'],
 ['Senior','Consumer','Support intermittent video access','Help a learner continue lessons with unreliable connectivity.','Downloads consume storage and become outdated.','Clarify offline availability, sync progress, and resolve conflicts.'],
 ['Senior','Search','Find a government service','Help someone discover eligibility without knowing official terminology.','Wrong eligibility guidance can waste time or exclude people.','Use plain-language questions, authoritative sources, and clear uncertainty and assistance paths.'],
 ['Senior','Craft','Make a usable interface excellent','A task works but feels inconsistent and laborious. Improve it.','Visual novelty can add friction without improving the task.','Inspect hierarchy, rhythm, content, feedback, and state transitions. Prioritise one coherent improvement.'],
 ['Senior','Enterprise','Resolve a permissions conflict','A user can see a record but cannot perform a needed action.','Revealing restricted information or request recipients may be inappropriate.','Explain the restriction at an appropriate level and offer an authorised recovery path.'],
 ['Senior','AI','Design a research assistant','Help a researcher synthesise documents and inspect supporting evidence.','Citations may not support the generated claim.','Keep evidence inspectable, distinguish synthesis from quotation, and support correction.'],
 ['Senior','Consumer','Improve checkout completion','Completion is low, but the reason is unknown. Frame the investigation.','Removing useful information may inflate completion while increasing returns.','Segment abandonment, investigate friction, and define guardrails before choosing a design.'],
 ['Senior','Enterprise','Improve a design-system contribution','Teams repeatedly create near-identical components. Design the contribution experience.','Governance can become a bottleneck.','Define reuse criteria, review ownership, documentation, and a lightweight exception path.'],
 ['Stretch','Search','Search across languages','Design search for multilingual India, including mixed-script queries.','Language and literacy preferences vary by task.','Investigate real query behaviour, support correction, and evaluate relevance by language and context.'],
 ['Stretch','AI','Prevent expensive AI mistakes','Design assistance where a wrong recommendation has a serious cost.','A confidence indicator may be mistaken for a guarantee.','Define prohibited actions, evidence requirements, independent validation, escalation, and evaluation before automation.'],
 ['Stretch','Enterprise','Coordinate an incident','Design collaboration when multiple teams respond to a service outage.','Updates are incomplete and ownership changes under pressure.','Prioritise shared state, roles, timestamps, acknowledgements, and an auditable timeline.'],
 ['Stretch','Consumer','Handoff between devices','Move a task from a phone to a desktop without confusion.','The devices may disagree about the latest state.','Define the handoff boundary, identity, progress, conflict handling, and fallback.'],
 ['Stretch','Accessibility','Use a watch in five seconds','Design a useful on-the-go interaction with very little attention.','Precision, distraction, and accidental actions matter.','Reduce the task to an essential decision and use appropriate feedback and recovery.'],
 ['Stretch','AI','Approve every agent action','Design an agent workflow where people must approve each external action.','Approval fatigue can turn review into automatic clicking.','Make proposed changes legible, batch only where safe, and preserve the ability to edit or reject.'],
 ['Stretch','Consumer','Design for a billion users','Scale a successful local product across regions and device capabilities.','One global average can hide serious failures in particular groups.','Choose segments and constraints, then evaluate access, localisation, performance, support, and governance.'],
 ['Stretch','Enterprise','Migrate a familiar workflow','Replace a legacy tool used by experts without destroying their efficiency.','A simpler first impression may hide more work for frequent users.','Observe expert shortcuts, compare migration strategies, and measure task quality during transition.'],
 ['Stretch','AI','Design memory users can control','Make an assistant’s remembered context understandable and correctable.','An old memory can be wrong, sensitive, or applied in the wrong context.','Show what is remembered and why, with scope, editing, forgetting, and clear effects.'],
 ['Stretch','Accessibility','Design for first-time smartphone users','Help someone complete a necessary service task independently.','Icon familiarity, literacy, and connectivity cannot be assumed.','Study context, reduce hidden interactions, support assistance, and test comprehension.'],
 ['Stretch','Search','Improve discovery with no terminology','Help a person search for a concept they cannot name.','Suggestions can prematurely narrow their intent.','Compare examples, guided clarification, and exploratory browsing. Preserve recovery from a wrong interpretation.'],
 ['Stretch','Enterprise','Remove a workflow entirely','Operators reconcile data between two systems every morning. Reframe the work.','Automation may move invisible errors downstream.','Compare better manual tools, exception-led review, and eliminating duplicate data entry at the source.'],
 ['Stretch','Consumer','Explain a misleading success metric','A new feature improves conversion but reduces repeat use. What do you do?','Cohort changes and short-term effects may be confounded.','Inspect cohorts and guardrails, research the changed experience, and design an experiment that tests the mechanism.'],
 ['Stretch','AI','Remove AI from your concept','A model is too slow and expensive. Preserve the user value without it.','The team may be attached to the proposed technology.','Identify the essential job and compare structured inputs, rules, defaults, search, and human assistance.'],
 ['Stretch','Accessibility','Design a cross-device public service','Someone begins on a shared phone and completes a service at a kiosk.','Identity, privacy, unfinished progress, and assisted use intersect.','Map handoff and consent, minimise exposed information, preserve progress safely, and design failure recovery.']
];
export const challenges=challengeSeeds.map((c,i)=>({id:i+1,level:c[0],category:c[1],title:c[2],prompt:c[3],risk:c[4],notes:c[5]}));
export const lessons=[
 {title:'Frame the decision',category:'Product thinking',body:'Begin with the decision the team needs to make. Separate the requested feature from the user job, the business outcome, and the uncertainty. A useful problem statement identifies who struggles, in what situation, and what better outcome would mean.',example:'“Add a dashboard” may hide a need to notice overdue cases early. Compare a dashboard with targeted alerts and changing the process that creates overdue cases.',say:'The assumption I want to test first is…',task:'Rewrite one real feature request as a problem. Name evidence that could prove the problem is smaller than you think.',weak:'Starting with a favourite framework or screens before identifying the decision.'},
 {title:'Choose evidence for a reason',category:'Research',body:'Pick a research method according to the uncertainty. Observation reveals behaviour; interviews explore context and reasoning; usability tests examine an interaction; analytics reveals patterns. Proxy evidence is useful when direct access is unavailable, but label its limits.',example:'If people abandon a form, analytics can locate drop-off; a usability session can reveal whether confusing requirements or an interaction failure explains it.',say:'This evidence supports X, but it does not yet establish Y.',task:'For a portfolio decision, list what you observed, what you inferred, and what you still do not know.',weak:'Saying “users wanted it” without describing the participants, method, or limitations.'},
 {title:'Conventional, reframed, radical',category:'Product judgment',body:'Generate an expected approach, a reframed approach that changes the mental model, and a radical approach that questions whether the work must exist. Compare value, familiarity, feasibility, accessibility, risk, and scalability. Novelty is not itself evidence of quality.',example:'For reconciling records: improve the table; show only exceptions; eliminate duplicate entry at the source. Each option creates different operational and trust requirements.',say:'The conventional approach assumes… If we challenge that assumption…',task:'Generate all three approaches before polishing one. Name the strongest reason to reject your favourite.',weak:'Calling a different visual style an innovative product idea.'},
 {title:'Craft beyond usability',category:'Interaction craft',body:'An interface can be usable yet feel mediocre because hierarchy, spacing, language, states, and transitions do not reinforce one another. Inspect the complete task, including focus, loading, interruption, failure, and recovery. Explain choices through the task and context.',example:'A save button with no feedback leaves uncertainty even if saving succeeds. A clear saved state and recovery from failure make the interaction feel complete.',say:'I made this information prominent because the next decision depends on it.',task:'Pick one screen. Improve hierarchy, one piece of content, and one state. Explain what you deliberately left unchanged.',weak:'A laundry list of visual opinions with no user or task context.'},
 {title:'Design systems are shared decisions',category:'Systems',body:'A component library is only part of a system. Semantic tokens, patterns, content rules, accessibility, ownership, contribution, and deprecation help teams make coherent decisions. Reuse existing semantics when they fit; extend deliberately; create new components when the interaction genuinely differs.',example:'A danger action needs more than a red token. Its pattern may need a clear consequence, appropriate confirmation, permissions, and recovery.',say:'The component API should make valid states easy and contradictory states difficult.',task:'Document a component’s inputs, states, keyboard behaviour, error cases, and adoption criteria.',weak:'Measuring success only by the number of components.'},
 {title:'A metric improved. Did the product?',category:'Measurement',body:'Connect an outcome metric to plausible user value and use input metrics to diagnose behaviour. Guardrails reveal costs such as errors, returns, support load, or exclusion. Inspect cohorts and the measurement window; a before-and-after change does not automatically establish causation.',example:'Faster ticket closure can coexist with more reopened tickets. Track resolution quality and rework alongside time.',say:'I would pair that success metric with this guardrail…',task:'Choose one feature. Define an outcome, two diagnostic measures, and two guardrails. Explain a misleading result.',weak:'Using engagement or acceptance as a universal proxy for user value.'},
 {title:'Understand the system underneath',category:'Technical fluency',body:'A client displays and gathers input; a server coordinates data and rules. APIs exchange structured information. Authentication establishes identity; authorisation decides allowed actions. Latency, caching, pagination, and stale data shape what users can see and safely do.',example:'Optimistic UI can make a reversible reaction feel immediate. A consequential transaction may need confirmation from the authoritative system before showing success.',say:'What happens if the request succeeds but the response never reaches the user?',task:'Map one interaction from input to server response. Design loading, timeout, duplicate retry, and permission failure.',weak:'Treating every failure as the same generic error toast.'},
 {title:'AI proposes; authority is designed',category:'AI design',body:'AI outputs can vary and be wrong. Start with a job where AI offers value, specify inputs and grounding, and design review, correction, fallback, and evaluation. An authoritative system should still validate permissions and enforce transaction rules.',example:'A support copilot may draft a resolution. A separate permission check decides whether the agent can execute the change. Sources and undo do not replace authorisation.',say:'The model can suggest this; the product must independently validate that.',task:'Draw a boundary around what the model may propose, what a person approves, and what the system enforces.',weak:'Adding a confidence percentage without knowing how it is calibrated or understood.'},
 {title:'Seniority through decisions',category:'Leadership',body:'Demonstrate seniority by showing how you created clarity, identified risk, compared alternatives, helped others contribute, and followed through. Titles and years do not explain your contribution. Give the other side of a disagreement a fair account.',example:'A useful conflict story explains the engineer’s cost concern, the user outcome, the options explored, who decided, and what happened.',say:'There were two constraints pulling in opposite directions…',task:'Prepare one story of influence, one of failure, and one of improving another person’s work.',weak:'Presenting yourself as the only person who cared about users or quality.'},
 {title:'Defend the portfolio honestly',category:'Portfolio',body:'For each project, distinguish evidence, assumptions, prototype behaviour, and shipped outcomes. Make your personal decisions visible. If metrics are unavailable, describe the qualitative evidence and its limits. Keep confidential material out of practice exports.',example:'“We tested a prototype with participants” is different from “the product improved retention”. Claim only what the evidence supports.',say:'The evidence is not strong enough to claim… What I can show is…',task:'Audit one case study with Verified, Needs evidence, and Do not claim yet labels.',weak:'A polished process story that never explains a hard choice or the actual outcome.'},
 {title:'Speak in layers',category:'Communication',body:'Start with the answer, then develop it. In 30 seconds give the headline and one concrete example. In two minutes add the context, decision, trade-off, and result. In five minutes include evidence, alternatives, collaboration, and learning. Pause to check alignment.',example:'After an interruption, acknowledge the question, answer it directly, and bridge back only if needed: “That changes the constraint. I would revise…”',say:'The short answer is… The reason is… A concrete example is…',task:'Record the same decision at all three lengths. Remove background that does not change the listener’s understanding.',weak:'Memorising paragraphs or treating uninterrupted talking as success.'},
 {title:'Use company lenses carefully',category:'Interview preparation',body:'Use Apple practice to examine platform conventions, restraint, accessibility, and interaction detail. Use Google practice to examine evidence, scale, ecosystems, and inclusion. Use Atlassian practice to examine enterprise roles, permissions, workflow complexity, and AI collaboration. These are learning lenses, not verified hiring rubrics.',example:'The same approval flow can be critiqued for native interaction quality, international scale, or enterprise governance.',say:'For this role, the product context suggests I should emphasise…',task:'Read the actual job description and recruiter guidance. Select two case studies and the decisions most relevant to that role.',weak:'Assuming every team at a company follows one interview format.'}
];
export const resources=[
 ['Apple Human Interface Guidelines','Platform patterns, interaction, accessibility','https://developer.apple.com/design/human-interface-guidelines/','Inspect one control in a real app. Explain where its platform behaviour helps.'],
 ['Material Design','Components, layout, and interaction','https://m3.material.io/','Compare a component’s guidance with one implementation you use.'],
 ['Google People + AI Guidebook','Human-centred AI decisions','https://pair.withgoogle.com/guidebook/','Apply one principle to the ticket-resolution challenge.'],
 ['Atlassian Design','Enterprise patterns and AI design','https://atlassian.design/','Study an enterprise pattern and sketch its failure state.'],
 ['W3C Web Accessibility Initiative','Accessibility standards and techniques','https://www.w3.org/WAI/','Choose one guideline and check a complete task with a keyboard.'],
 ['Figma Help Center','Components, variables, and prototyping','https://help.figma.com/','Build a small component that demonstrates what you studied.'],
 ['GOV.UK Design System','Public-service patterns and content','https://design-system.service.gov.uk/','Rewrite a confusing service form using plain language.'],
 ['Microsoft Fluent','Cross-platform design-system guidance','https://fluent2.microsoft.design/','Compare a pattern with its Material equivalent and explain context.']
];
